# Generated by Django 4.0.4 on 2022-05-26 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vital_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='user',
        ),
        migrations.AddField(
            model_name='vital',
            name='user',
            field=models.ManyToManyField(related_name='user_vital', to=settings.AUTH_USER_MODEL),
        ),
    ]
