# Generated by Django 4.0.4 on 2022-05-25 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vital_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_vital', to=settings.AUTH_USER_MODEL),
        ),
    ]
