# Generated by Django 4.0.4 on 2022-05-26 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vital_input', '0002_remove_vital_user_vital_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='user',
        ),
        migrations.AddField(
            model_name='vital',
            name='vital_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vital', to=settings.AUTH_USER_MODEL),
        ),
    ]
