# Generated by Django 4.0.4 on 2022-05-27 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='corona_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_symptom_onset', models.DateField(null=True, verbose_name='発症日')),
                ('date_of_positive', models.DateField(null=True, verbose_name='検査陽性日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_corona_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '発症日と陽性日',
                'db_table': 'user_corona_history',
            },
        ),
    ]
