# Generated by Django 4.0.4 on 2022-05-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_corona_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='corona_history',
            new_name='CoronaHistory',
        ),
    ]
